# Generated by Django 4.1 on 2022-08-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_profile_about_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='profile_birthday',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cover_image',
            new_name='profile_cover_image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='profile_followers',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='profile_following',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='profile_gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_profile_pic',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_about_me',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
