# Generated by Django 4.1 on 2022-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_birthday_profile_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_about_me',
            field=models.CharField(default='About Me', max_length=250, null=True),
        ),
    ]
