# Generated by Django 4.1 on 2022-08-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='content',
            new_name='website_content',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='link',
            new_name='website_link',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='logo',
            new_name='website_logo',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='title',
            new_name='website_title',
        ),
    ]
