# Generated by Django 4.1 on 2022-08-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_subcomment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='post_picture',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='post_user',
        ),
    ]
