# Generated by Django 4.1 on 2022-08-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_picture_post_post_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_user',
            new_name='user',
        ),
    ]
